{{- if .Values.NewPeerOrgs }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-newpeerorg-configtx.yaml
data:
  configtx.yaml: |- 
    {{ $.Files.Get "newpeerorg-configtx.yaml" | b64enc }}

{{- end }} {{- /* if NewPeerOrgs */ -}}     
